algo=input('Digite algo: ')
print('O tipo primitivo desse valor é:',type)
print('Só tem espaços?',algo.isspace())
print('É um número?',algo.isnumeric())
print('É alfabetico?',algo.isalpha())
print('é alphanumerico?',algo.isalnum())
print('Esta em maiusculo?',algo.isupper())
print('Esta em minusculo?',algo.islower())
print('Esta capitalizada?',algo.istitle())
